from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class AIWorldSeed:
    name: str
    currency_code: str
    personality: str
    player_name: str
    player_id: int


NATION_NAMES = [
    "Avalon",
    "Ardenia",
    "Briarhold",
    "Caledon",
    "Dunwich",
    "Eldoria",
    "Fairmont",
    "Grayhaven",
    "Highmoor",
    "Ivoryreach",
    "Jasperland",
    "Kingsley",
    "Larkspur",
    "Merewood",
    "Northvale",
    "Oakridge",
    "Pinecrest",
    "Queensreach",
    "Rosemont",
    "Silverlake",
    "Thornfield",
    "Umberland",
    "Valewick",
    "Westford",
    "Yorkhaven",
    "Amberfall",
    "Brighton",
    "Crestwood",
    "Driftwood",
    "Eastmere",
    "Foxglove",
    "Greenhaven",
    "Hawthorne",
    "Ironvale",
    "Juniper",
    "Kestrel",
    "Lakewood",
    "Moonridge",
    "Newford",
    "Orchard",
    "Peakland",
    "Quarry Bay",
    "Ravenwood",
    "Stonehaven",
    "Timberland",
    "Uplands",
    "Violetmere",
    "Willowdale",
    "Xenford",
    "Yarrow",
    "Zephyrland",
    "Ashbourne",
    "Bluehaven",
    "Cedarfall",
    "Doverland",
    "Elmstead",
    "Frostmere",
    "Goldhaven",
    "Harborwick",
    "Isleford",
    "Kingsport",
    "Longmere",
    "Mistvale",
    "Oakmont",
    "Portland",
    "Queensvale",
    "Redhaven",
    "Sunridge",
    "Tranquil",
    "Unionvale",
    "Windermere",
    "Yorkshire",
    "Amberwick",
    "Belltown",
    "Clearwater",
    "Deepwood",
    "Evermere",
    "Fallowland",
    "Glenhaven",
    "Heartland",
    "Ironwood",
    "Joyvale",
    "Knollmere",
    "Linden",
    "Meadowbrook",
    "Northstar",
    "Oldcastle",
    "Pemberton",
    "Quickwater",
    "Riverdale",
    "Southvale",
    "Trinity",
    "Underhill",
    "Westhaven",
    "Yellowstone",
    "Zionvale",
    "Appleford",
    "Brookshire",
    "Crownvale",
    "Dreamhaven",
]

PLAYER_NAMES = [
    "Alex Carter",
    "Alex Brooks",
    "Alex Bennett",
    "Alex Parker",
    "Alex Turner",
    "Ryan Carter",
    "Ryan Brooks",
    "Ryan Bennett",
    "Ryan Parker",
    "Ryan Turner",
    "Mason Carter",
    "Mason Brooks",
    "Mason Bennett",
    "Mason Parker",
    "Mason Turner",
    "Ethan Carter",
    "Ethan Brooks",
    "Ethan Bennett",
    "Ethan Parker",
    "Ethan Turner",
    "Noah Carter",
    "Noah Brooks",
    "Noah Bennett",
    "Noah Parker",
    "Noah Turner",
    "Liam Carter",
    "Liam Brooks",
    "Liam Bennett",
    "Liam Parker",
    "Liam Turner",
    "Lucas Carter",
    "Lucas Brooks",
    "Lucas Bennett",
    "Lucas Parker",
    "Lucas Turner",
    "Owen Carter",
    "Owen Brooks",
    "Owen Bennett",
    "Owen Parker",
    "Owen Turner",
    "Jack Carter",
    "Jack Brooks",
    "Jack Bennett",
    "Jack Parker",
    "Jack Turner",
    "Henry Carter",
    "Henry Brooks",
    "Henry Bennett",
    "Henry Parker",
    "Henry Turner",
    "Leo Carter",
    "Leo Brooks",
    "Leo Bennett",
    "Leo Parker",
    "Leo Turner",
    "Theo Carter",
    "Theo Brooks",
    "Theo Bennett",
    "Theo Parker",
    "Theo Turner",
    "Adam Carter",
    "Adam Brooks",
    "Adam Bennett",
    "Adam Parker",
    "Adam Turner",
    "Evan Carter",
    "Evan Brooks",
    "Evan Bennett",
    "Evan Parker",
    "Evan Turner",
    "Nolan Carter",
    "Nolan Brooks",
    "Nolan Bennett",
    "Nolan Parker",
    "Nolan Turner",
    "Caleb Carter",
    "Caleb Brooks",
    "Caleb Bennett",
    "Caleb Parker",
    "Caleb Turner",
    "Miles Carter",
    "Miles Brooks",
    "Miles Bennett",
    "Miles Parker",
    "Miles Turner",
    "Logan Carter",
    "Logan Brooks",
    "Logan Bennett",
    "Logan Parker",
    "Logan Turner",
    "Julian Carter",
    "Julian Brooks",
    "Julian Bennett",
    "Julian Parker",
    "Julian Turner",
    "Aaron Carter",
    "Aaron Brooks",
    "Aaron Bennett",
    "Aaron Parker",
    "Aaron Turner",
]

PERSONALITIES = (
    "balanced",
    "value",
    "momentum",
    "conservative",
    "aggressive",
)

AI_USER_ID_BASE = 8_000_000_000_000_000_000


def _currency_code(name: str, index: int) -> str:
    compact = "".join(ch for ch in name.upper() if ch.isalpha())
    base = (compact[:4] or f"AI{index:02d}")[:4]
    if base not in _used_codes:
        _used_codes.add(base)
        return base

    suffix = chr(ord("A") + (index % 26))
    candidate = (base[:3] + suffix)[:4]
    if candidate in _used_codes:
        candidate = f"{index:04d}"[-4:]
    _used_codes.add(candidate)
    return candidate


_used_codes: set[str] = set()

AI_WORLD_SEEDS = tuple(
    AIWorldSeed(
        name=name,
        currency_code=_currency_code(name, index),
        personality=PERSONALITIES[index % len(PERSONALITIES)],
        player_name=PLAYER_NAMES[index],
        player_id=AI_USER_ID_BASE + index + 1,
    )
    for index, name in enumerate(NATION_NAMES)
)

del _used_codes
