"""Make BigInteger history identifiers auto-generated.

Revision ID: 0006_bigint_history_identities
Revises: 0005_nation_management
"""

from alembic import op


revision = "0006_bigint_history_identities"
down_revision = "0005_nation_management"
branch_labels = None
depends_on = None


def _add_identity(table_name: str) -> None:
    op.execute(
        f"""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_attribute
                WHERE attrelid = '{table_name}'::regclass
                  AND attname = 'id'
                  AND attidentity IN ('a', 'd')
            ) THEN
                ALTER TABLE {table_name}
                ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
            END IF;
        END
        $$;
        """
    )
    op.execute(
        f"""
        SELECT setval(
            pg_get_serial_sequence('public.{table_name}', 'id'),
            COALESCE((SELECT MAX(id) FROM public.{table_name}), 0) + 1,
            false
        )
        """
    )


def upgrade() -> None:
    _add_identity("user_activities")
    _add_identity("rate_history")


def downgrade() -> None:
    op.execute(
        """
        ALTER TABLE user_activities
        ALTER COLUMN id DROP IDENTITY IF EXISTS
        """
    )
    op.execute(
        """
        ALTER TABLE rate_history
        ALTER COLUMN id DROP IDENTITY IF EXISTS
        """
    )
