"""Make BigInteger history identifiers auto-generated.

Revision ID: 0006_bigint_history_identities
Revises: 0005_nation_management
"""

from alembic import op


revision = "0006_bigint_history_identities"
down_revision = "0005_nation_management"
branch_labels = None
depends_on = None


def _ensure_generated(table_name: str) -> None:
    op.execute(
        f"""
        DO $$
        DECLARE
            seq_name text;
            current_max bigint;
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_attribute a
                LEFT JOIN pg_attrdef d
                  ON d.adrelid = a.attrelid
                 AND d.adnum = a.attnum
                WHERE a.attrelid = '{table_name}'::regclass
                  AND a.attname = 'id'
                  AND (
                      a.attidentity IN ('a', 'd')
                      OR (
                          d.adbin IS NOT NULL
                          AND pg_get_expr(d.adbin, d.adrelid) LIKE 'nextval(%%'
                      )
                  )
            ) THEN
                ALTER TABLE {table_name}
                ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
            END IF;

            SELECT pg_get_serial_sequence('public.{table_name}', 'id')
              INTO seq_name;

            IF seq_name IS NOT NULL THEN
                SELECT COALESCE(MAX(id), 0)
                  INTO current_max
                  FROM public.{table_name};

                PERFORM setval(
                    seq_name::regclass,
                    current_max + 1,
                    false
                );
            END IF;
        END
        $$;
        """
    )


def upgrade() -> None:
    _ensure_generated("user_activities")
    _ensure_generated("rate_history")


def downgrade() -> None:
    op.execute(
        """
        ALTER TABLE user_activities
        ALTER COLUMN id DROP IDENTITY IF EXISTS
        """
    )
    op.execute(
        """
        ALTER TABLE rate_history
        ALTER COLUMN id DROP IDENTITY IF EXISTS
        """
    )
